# Generated by Django 5.2.15 on 2026-06-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=100)),
                ('menu_price', models.IntegerField()),
                ('menu_description', models.TextField()),
                ('menu_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
